### ISSUE TITLE
4D Freezing 15 R2

### ISSUE THREAD

**Issue by DenisMik** [miyako/4d-plugin-common-crypto#3]
Hi Miyako, 
We have started using your 4D Common Crypto Plugin earlier this year and since we deployed to sites we started to notice a strange issues: 4D datafile is getting locked fully and not able to perform any operations.

This happens for Server – Client environment only, 4D Client is freezes then 4D server freezes as well. We have been trying to find a solution for this problem for months and we started to removing the Crypto plugin from the sites and it seems fixing the issue – but not 100% sure as we do not know the root cause and not able to replicate it.

Are you aware of any issues with Crypto Plugin that would possibly cause freezing?
Thanks you

**Comment by miyako** [comment]
> 2017/07/11 8:58、Denis Mikheev <notifications@github.com> のメール：
> Are you aware of any issues with Crypto Plugin that would possibly cause freezing?

Hello,

It would be weird if I was aware of such issues and kept silent about it. Would you mind sharing information about the platform OS, the exact version of the plugin (create date), why you are using an transitional version of 4D (15R2), the network layer setting (new or old), why you think the network issue is caused by the plugin? Do you have debug log, request log, diagnostic log to prove it?


宮古　啓介
テクニカルアカウントマネージャー


株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel: 03-6427-8441
Fax: 03-6427-8449

Keisuke.Miyako@4d.com
www.4D.com/jp

**Comment by DenisMik** [comment]
Hi Miyako,
1) Create date: 1 December 2015
2) 15 R2 - it is a very time consuming process for us to migrate to newer versions due to regression testing
3) OS - 4D Freezes on Win 7, Win 8 and Win 10.
4) We use old network layer - as identified multiple problems with a new one
5) It is an assumption, we do not know what causing 4D to freeze. We have around 20 sites constantly reporting freezing almost on a daily basis. Once we remove the plugin no freezing reported. We monitor it it on a daily bases no freezing reports for 3 + weeks.

I repeat myself it is an assumption that component causing 4D to freeze. We do not have any logs to prove that and I am reaching for your help.
Thanks

**Comment by miyako** [comment]
the date looks pretty old. would you mind trying the latest version on this repository?

**Comment by DenisMik** [comment]
I will bring it up for product to review and will see.
Thank you
